-- ---@type Node
-- local node = require('AI.USER_AI.BT.nodes')
-- ---@type Condition
-- local condition = require('AI.USER_AI.BT.conditions')
-- local Homun = require('AI.USER_AI.UTIL.Homun')
--
-- ---@type Homun
-- local eleanor = Homun(MySkills, MyCooldown)
--
-- ---@param skillId number
-- ---@param target number
-- ---@param opts SkillOpts
-- ---@return Status
-- local function cast(skillId, target, opts)
--   return eleanor.castSkill(skillId, target, opts)
-- end
--
-- local silver = {}
-- function silver.condition()
--   return eleanor.isSkillCastable(MH_SILVERVEIN_RUSH)
-- end
-- function silver.cast()
--   return cast(MH_SILVERVEIN_RUSH, MyEnemy, { targetType = 'target', keepRunning = false })
-- end
-- local midnight = {}
-- function midnight.condition()
--   return eleanor.isSkillCastable(MH_MIDNIGHT_FRENZY)
-- end
-- function midnight.cast()
--   return cast(MH_MIDNIGHT_FRENZY, MyEnemy, { targetType = 'target', keepRunning = false })
-- end
-- local sonic = {}
-- function sonic.condition()
--   return eleanor.isSkillCastable(MH_SONIC_CRAW)
-- end
-- function sonic.cast()
--   if not silver.condition() or not midnight.condition() then
--     return cast(MH_SONIC_CRAW, MyEnemy, { targetType = 'target', keepRunning = true })
--   end
--   return cast(MH_SONIC_CRAW, MyEnemy, { targetType = 'target', keepRunning = false })
-- end
-- local tinder = {}
-- function tinder.condition()
--   return eleanor.isSkillCastable(MH_TINDER_BREAKER)
-- end
-- function tinder.cast()
--   return cast(MH_TINDER_BREAKER, MyEnemy, { targetType = 'target', keepRunning = false })
-- end
-- local cbc = {}
-- function cbc.condition()
--   return eleanor.isSkillCastable(MH_CBC)
-- end
-- function cbc.cast()
--   return cast(MH_CBC, MyEnemy, { targetType = 'target', keepRunning = false })
-- end
-- local eqc = {}
-- function eqc.condition()
--   return eleanor.isSkillCastable(MH_EQC)
-- end
-- function eqc.cast()
--   return cast(MH_EQC, MyEnemy, { targetType = 'target', keepRunning = false })
-- end
--
-- local BattleComboSequence = Condition(
--   Sequence({
--     Condition(sonic.cast, sonic.condition),
--     Condition(Delay(silver.cast, 2.0), silver.condition),
--     Condition(Delay(midnight.cast, 2.0), midnight.condition),
--   }),
--   Inversion(condition.enemyIsNotInAttackSight)
-- )
-- local ClawComboSequence = Condition(
--   Sequence({
--     Condition(tinder.cast, tinder.condition),
--     Condition(Delay(cbc.cast, 2.0), cbc.condition),
--     Condition(Delay(eqc.cast, 2.0), eqc.condition),
--   }),
--   Inversion(condition.enemyIsNotInAttackSight)
-- )
-- local BattleComboMode = Sequence({
--   node.chaseEnemy,
--   BattleComboSequence,
-- })
-- local ClawComboMode = Sequence({
--   node.chaseEnemy,
--   ClawComboSequence,
-- })
-- local AttackAndChaseGainSpheres = Parallel({
--   node.EleanorBasicAttack,
--   node.chaseEnemy,
-- })
-- local combat = Selector({
--   Condition(BattleComboMode, BATTLE_MODE.isBattleMode),
--   Condition(ClawComboMode, BATTLE_MODE.isClawMode),
--   Condition(AttackAndChaseGainSpheres, Inversion(condition.hasAllSpheres)),
--   Condition(node.attackAndChase, Inversion(sonic.condition)),
-- })
-- return Condition(eleanor.root(combat), IsEleanor)
