IDLE_ST = 0 -- The Homunculus will rest; and does not perform any actions.
FOLLOW_ST = 1 -- the Homunculus will travel towards its owner.
CHASE_ST = 2 -- The Homunculus will follow the targeted object.
ATTACK_ST = 3 -- The Homunculus will continuously perform the action of attacking the targeted object.
MOVE_CMD_ST = 4
STOP_CMD_ST = 5
ATTACK_OBJECT_CMD_ST = 6
ATTACK_AREA_CMD_ST = 7
PATROL_CMD_ST = 8
HOLD_CMD_ST = 9
SKILL_OBJECT_CMD_ST = 10
SKILL_AREA_CMD_ST = 11
FOLLOW_CMD_ST = 12
OWNER_DAMAGED = 13
OWNER_LOST_HEALTH = 14
OWNER_DYING = 15
OWNER_DEAD = 16
OWNER_SITTING = 17
